podTemplate(containers: [
    containerTemplate(name: 'jnlp', image: 'jenkins/inbound-agent:4.7-1', args: '${computer.jnlpmac} ${computer.name}'),
    containerTemplate(name: 'maven', image: 'maven:3.8.1-jdk-8', command: 'sleep', args: '99d'),
    containerTemplate(name: 'golang', image: 'golang:1.16.5', command: 'sleep', args: '99d')
  ]) {

    node(POD_LABEL) {
        stage('Get a Maven project') {
            git 'https://github.com/jenkinsci/kubernetes-plugin.git'
            container('maven') {
                stage('Build a Maven project') {
                    sh 'mvn -B -ntp clean install'
                }
            }
        }

        stage('Get a Golang project') {
            git url: 'https://github.com/hashicorp/terraform.git', branch: 'main'
            container('golang') {
                stage('Build a Go project') {
                    sh '''
                    mkdir -p /go/src/github.com/hashicorp
                    ln -s `pwd` /go/src/github.com/hashicorp/terraform
                    cd /go/src/github.com/hashicorp/terraform && make
                    '''
                }
            }
        }

    }
}
// podTemplate(containers: [
//   containerTemplate(name: 'jnlp', image: 'jenkins/inbound-agent:4.7-1', args: '${computer.jnlpmac} ${computer.name}', command: ''),
//   containerTemplate(name: 'terraform', image: 'hashicorp/terraform:1.0.5',  command: '')
//   ],
//   ) {

//     node(POD_LABEL) {
//           stage('TF init & validate') {
//             steps {
//               container('terraform') {
//                 sh '''
//                   terraform init
//                   terraform validate
//                 fi'''
//               }
//             }
//     }

//     }
// }

// pipeline {
//   containerTemplate(name: 'terraform', image: 'hashicorp/terraform:1.0.5')
//   agent any
//   stages {
//     // [START tf-init, tf-validate]
//     stage('TF init & validate') {
//       steps {
//         container('terraform') {
//           sh '''
//             terraform init
//             terraform validate
//           fi'''
//         }
//       }
//     }
//     // [END tf-init, tf-validate]

//     // [START tf-plan]
//     stage('TF plan') {
//       when { anyOf {branch "prod";branch "dev";changeRequest() } }
//       steps {
//         container('terraform') {
//           sh '''
//           if [[ $CHANGE_TARGET ]]; then
//             TARGET_ENV=$CHANGE_TARGET
//           else
//             TARGET_ENV=$BRANCH_NAME
//           fi
         
//           if [ -d "example-pipelines/environments/${TARGET_ENV}/" ]; then
//             cd example-pipelines/environments/${TARGET_ENV}
//             terraform plan
//           else
//             for dir in example-pipelines/environments/*/
//             do 
//               cd ${dir}
//               env=${dir%*/}
//               env=${env#*/}
//               echo ""
//               echo "*************** TERRAFOM PLAN ******************"
//               echo "******* At environment: ${env} ********"
//               echo "*************************************************"
//               terraform plan || exit 1
//               cd ../../../
//             done
//           fi'''
//         }
//       }
//     }
//     // [END tf-plan]

//     // [START tf-apply]
//     stage('TF Apply') {
//       when { anyOf {branch "prod";branch "dev" } }
//       steps {
//         container('terraform') {
//           sh '''
//           TARGET_ENV=$BRANCH_NAME

//           if [ -d "example-pipelines/environments/${TARGET_ENV}/" ]; then
//             cd example-pipelines/environments/${TARGET_ENV}
//             terraform apply -input=false -auto-approve
//           else
//             echo "*************** SKIPPING APPLY ******************"
//             echo "Branch '$TARGET_ENV' does not represent an official environment."
//             echo "*************************************************"
//           fi'''
//         }
//       }
//     }
//     // [END tf-apply]
//   }
// }
